const messages = {
  success: "Operation successful",
  created: "Resource created successfully",
  accepted: "Request accepted",
  bad_request: "Bad request",
  unauthorized: "Unauthorized access",
  token_expired: "Token has expired",
  invalid_token: "Invalid token",
  payment_required: "Payment required",
  forbidden: "Forbidden access",
  not_found: "Resource not found",
  employee_not_found: "Employee not found",
  employee_created: "Employee created successfully",
  employee_deleted: "Employee deleted successfully",
  employee_updated: "Employee updated successfully",
  method_not_allowed: "Method not allowed",
  not_acceptable: "Not acceptable",
  proxy_authentication_required: "Proxy authentication required",
  internal_server_error: "Internal server error",
  not_implemented: "Not implemented",
  bad_gateway: "Bad gateway",
  data_fetched: "Data fetched successfully",
  attendance_checked_in: "Attendance checked in successfully",
  attendance_checked_out: "Attendance checked out successfully",
  attendance_checked_found: "Attendance already checked in today",
  attendance_checked_out_found: "Attendance already checked out today",
  attendance_check_not_found: "Attendance not found for today",
  attendance_updated: "Attendance updated successfully",
  attendance_not_found: "Attendance record not found",
  unauthorized_edit: "You are not authorized to edit this attendance record",
  attendance_update_pending: "Attendance update is pending approval",
  attendance_approved: "Attendance changes approved",
  attendance_rejected: "Attendance changes rejected",
  no_pending_changes: "No pending changes to approve",
};

export default messages;