const messages = {
  success: "Operation successful",
  created: "Resource created successfully",
  accepted: "Request accepted",
  bad_request: "Bad request",
  unauthorized: "Unauthorized access",
  token_expired: "Token has expired",
  invalid_token: "Invalid token",
  payment_required: "Payment required",
  forbidden: "Forbidden access",
  not_found: "Resource not found",
  employee_not_found: "Employee not found",
  employee_created: "Employee created successfully",
  employee_deleted: "Employee deleted successfully",
  employee_updated: "Employee updated successfully",
  method_not_allowed: "Method not allowed",
  not_acceptable: "Not acceptable",
  proxy_authentication_required: "Proxy authentication required",
  internal_server_error: "Internal server error",
  not_implemented: "Not implemented",
  bad_gateway: "Bad gateway",
  data_fetched: "Data fetched successfully",
  attendance_checked_in: "Attendance checked in successfully",
  attendance_checked_out: "Attendance checked out successfully",
  attendance_checked_found: "Attendance already checked in today",
  attendance_checked_out_found: "Attendance already checked out today",
  attendance_check_not_found: "Attendance not found for today",
  attendance_updated: "Attendance updated successfully",
  attendance_not_found: "Attendance record not found",
  unauthorized_edit: "You are not authorized to edit this attendance record",
  attendance_update_pending: "Attendance update is pending approval",
  attendance_approved: "Attendance changes approved",
  attendance_rejected: "Attendance changes rejected",
  no_pending_changes: "No pending changes to approve",
  ROLE_CREATED: "Role created successfully",
  ROLES_FETCHED: "Roles fetched successfully",
  USER_CREATED: "User created successfully",
  USERS_FETCHED: "Users fetched successfully",
  ROLE_NOT_FOUND: "Role not found",
  ROLE_UPDATED: "Role updated successfully",
  USER_NOT_FOUND: "User not found",
  already_exists: "Resource already exists",
  
  // Messages for Leaves
  leave_created: "Leave request created successfully",
  leave_updated: "Leave request updated successfully",
  leave_deleted: "Leave request deleted successfully",
  leave_not_found: "Leave request not found",
  leave_already_exists: "Leave request already exists for this date",
  leave_approved: "Leave request approved successfully",
  leave_rejected: "Leave request rejected successfully",
  leave_already_processed: "Leave request has already been processed",
  invalid_leave_type: "Invalid leave type",
  invalid_leave_duration: "Invalid leave duration",
  insufficient_leave_balance: "Insufficient leave balance",
  
  // Messages for EmployeeLeaves
  employee_leaves_created: "Employee leaves record created successfully",
  employee_leaves_updated: "Employee leaves record updated successfully",
  employee_leaves_deleted: "Employee leaves record deleted successfully",
  employee_leaves_not_found: "Employee leaves record not found",
  employee_leaves_already_exists: "Employee leaves record already exists",
  invalid_holidays_pending: "Invalid holidays pending value",
  USER_FETCHED:"User fetched successfully",
};

export default messages;